### ISSUE TITLE
Return value of MadWeb\Initializer\Actions\Action::errorMessage() must be of the type string, null returned

### ISSUE THREAD

**Issue by kosmonowt** [mad-web/laravel-initializer#17]
- Laravel Version: 7.6.1
- Laravel Initializer Version: 3.1.0
- PHP Version: 7.4.x

### Description:

```
local.ERROR: Return value of MadWeb\Initializer\Actions\Action::errorMessage() must be of the type string, null returned {"exception":"[object] (TypeError(code: 0): Return value of MadWeb\\Initializer\\Actions\\Action::errorMessage() must be of the type string, null returned at /Library/WebServer/Documents/myproject/vendor/mad-web/laravel-initializer/src/Actions/Action.php:50)
[stacktrace]
#0 /Library/WebServer/Documents/myproject/vendor/mad-web/laravel-initializer/src/Run.php(36): MadWeb\\Initializer\\Actions\\Action->errorMessage()
#1 /Library/WebServer/Documents/myproject/vendor/mad-web/laravel-initializer/src/Run.php(49): MadWeb\\Initializer\\Run->run(Object(MadWeb\\Initializer\\Actions\\Artisan))
#2 /Library/WebServer/Documents/myproject/app/Update.php(31): MadWeb\\Initializer\\Run->artisan('down')
```

### Steps To Reproduce:

1. Manually run `php artisan down`
2. Create Update.php including `$run->artisan("down");`
3. Run `php artisan app:update`
4. ...
5. 🎉 `app:update` process failing with error above.

### Suggestions:
- I will give a hotfix attached to this issue.
- Please accept my pull request with an updated Action.php that at least doesn't make some continuous deployments crash every now and then.
- Later on, you may see if you can find another solution that handles those kinds of exception, maybe by handling `down` and `up` explicitly in your `Artisan.php`.

**Comment by slavarazum** [comment]
Fixed in [v3.1.1](https://github.com/mad-web/laravel-initializer/releases/tag/3.1.1)
